name: EC2 Auto Deploy on Push

on:
  push:
    branches:
      - main  # Workflow will trigger on push to the main branch

env:
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_PORT: ${{ secrets.EC2_PORT || 22 }} # Agar aapne EC2_PORT naam se secret banaya hai toh woh use karein
  PROJECT_PATH: /home/ubuntu/MERN-STACK-AZHAR      # Your project path on EC2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (on GitHub Actions Runner)
        uses: actions/checkout@v3
        with:
          ssh-known-hosts: ${{ env.DEPLOY_HOST }}

      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} -p ${{ env.DEPLOY_PORT }} "
            # Check if project directory exists, if not create it and clone the repo
            if [ ! -d \"${{ env.PROJECT_PATH }}\" ]; then
              mkdir -p \"${{ env.PROJECT_PATH }}\"
              cd \"${{ env.PROJECT_PATH }}\"
              git clone -b ${{ env.REPOSITORY_BRANCH }} \"${{ env.REPOSITORY_URL }}\" .
            else
              cd \"${{ env.PROJECT_PATH }}\"
              git pull origin ${{ env.REPOSITORY_BRANCH }}
            fi

            # Run Docker Compose commands
            if command -v docker-compose &> /dev/null
            then
              docker-compose down
              docker-compose up -d --build
              docker image prune -af
            else
              echo \"Error: docker-compose command not found. Please ensure Docker Compose is installed on the EC2 instance.\"
              exit 1
            fi
          "