name: EC2 Auto Deploy on Push

on:
  push:
    branches:
      - main  # Workflow will trigger on push to the main branch

env:
  EC2_HOST: ${{ secrets.DEPLOY_HOST }}
  EC2_USER: ${{ secrets.DEPLOY_USER }}
  EC2_PORT: ${{ secrets.EC2_PORT || 22 }}
  PROJECT_PATH: /home/ubuntu/MERN-STACK-AZHAR      # Your project path on EC2
  EC2_KEY: ${{ secrets.DEPLOY_KEY}}              # Added EC2_KEY to env

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} -p ${{ env.EC2_PORT }} "
            cd ${{ env.PROJECT_PATH }}
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker image prune -af
          "